### ISSUE TITLE
BUG: Get an error message when connecting to an existing RStab model for the first time

### ISSUE THREAD

**Issue by talSas** [Dlubal-Software/Dlubal_CSharp_Client#4] opened 2021-11-25 15:03 UTC
**Describe the bug**
API access fails when accessing an existing model for the first time. Provable Reproducible 

**To Reproduce**
1. Open a RStab9 Modell
2. Try an api access as seen in my source code ( sourcecode.png)
3. Execute Code

**Expected behavior**
Actually, I expect that the access will not fail first, especially since it works without problems when executing the code repeatedly. 

**Screenshots**
![ConnectionError](https://user-images.githubusercontent.com/83770956/143463370-cfa95f2b-b4f4-4cd6-b710-fea2c9365612.PNG)
![SourceCode](https://user-images.githubusercontent.com/83770956/143463551-f4a78847-83c8-4bd1-9a37-2a863b35de10.PNG)
**Desktop (please complete the follow

ing information):**
 - OS: e.g. WIN 10 PRO Version 10.0.19043 Build 19043
 -  RSTAB 9.01.0008
 -  Version 1? 

**Additional context**
Add any other context about the problem here
[Rstab9CoreDump.zip](https://github.com/Dlubal-Software/Dlubal_CSharp_Client/files/7603780/Rstab9CoreDump.zip)
.

**Comment by jarabroz** [comment] 2021-11-26 12:06
Hello @talSas ,

this issue was caused by development from other team. We fix this issue in the code of RFEM/RSTAB and it will be included in the next version of RFEM/RSTAB  - .0009 (ETA Tuesday 30/11).

**Comment by talSas** [comment] 2021-11-30 09:06
With version .0009 the bug no longer occurs.

**Closed** 2021-11-30 10:19 UTC
Labels: bug, invalid
